#! /bin/sh
#                    ___           ___         ___           ___
#     _____         /  /\         /  /\       /__/\         /__/\
#    /  /::\       /  /:/_       /  /::\     _\_ \:\       |  |::\
#   /  /:/\:\     /  /:/ /\     /  /:/\:\   /__/\ \:\      |  |:|:\
#  /  /:/ /::\   /  /:/ /::\   /  /:/ /:/  _\_ \:\ \:\   __|__|:|\:\
# /__/:/ /:/\:| /__/:/ /:/\:\ /__/:/ /:/  /__/\ \:\ \:\ /__/::::| \:\
# \  \:\/:/ /:/ \  \:\/:/ /:/ \  \:\/:/   \  \:\ \:\/:/ \  \:\~~\__\/
#  \  \::/ /:/   \  \::/ /:/   \  \::/     \  \:\ \::/   \  \:\
#   \  \:\/:/     \__\/ /:/     \  \:\      \  \:\/:/     \  \:\
#    \  \::/        /__/:/       \  \:\      \  \::/       \  \:\
#     \__\/         \__\/         \__\/       \__\/         \__\/
#
#

# Keybindings
pgrep -x sxhkd > /dev/null || sxhkd &

# Picom Compositor
picom --experimental-backends &

# Wallpaper
nitrogen --set-zoom ~/Pictures/Lamborghini.jpg &

# Launch Polybar
$HOME/.config/polybar/launch.sh &

# Workspace Setup
bspc monitor -d 1 2 3 4 5 6 7 8 9

# Window Setup
bspc config border_width         2

bspc config normal_border_color  \#93a1a1
bspc config active_border_color  \#29B6F6
bspc config focused_border_color \#29B6F6

bspc config window_gap          16

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Remove x cursor
xsetroot -cursor_name left_ptr &

# Focus window on hover
bspc config focus_follows_pointer true &

# Window Rules

# Terminal to First Workspace
bspc rule -a Alacritty desktop='^1' follow=on

# Browsers to Second Workspace
bspc rule -a Brave-browser desktop='^2' follow=on

bspc rule -a firefoxdeveloperedition desktop='^2' follow=on

# Code Editors to Third Workspace
bspc rule -a Code desktop='^3' follow=on

# File Manager to Fourth Workspace
bspc rule -a Org.gnome.Nautilus desktop='^4' follow=on
